### ISSUE TITLE
Cors package missing

### ISSUE THREAD

**Issue by plug-n-play** [mariadb-corporation/dev-example-todo#5]
https://github.com/mariadb-corporation/dev-example-todo/blob/master/api/nodejs/basic/server.js#L9

Cors package is missing from dependencies https://github.com/mariadb-corporation/dev-example-todo/blob/master/api/nodejs/basic/package.json

**Comment by rhedgpeth** [comment]
@plug-n-play I'll update the Sequelize project to include cors as well.

**Comment by rhedgpeth** [comment]
I've removed all things `cors`. I don't think it's needed, and I must have accidentally pushed something I wasn't meaning to.
